task: add_noise # must be one of add_noise / reverberate / freq_filter / de_noise
de_noise: noise # must be one of add_noise / reverberate /freq_filter
source_directory: data/LibriSpeech/test-clean
target_directory: data
urban_meta_path: data/urban_meta.csv
urban_path: data/UrbanSound8K
urban_sr: 48000
libri_sr: 16000
artifact_scaling_factor: 0.8
impulse_response_path: data/ImpulseResponses
ir_meta_path: data/ir_meta.csv
ir_keep_duration: True
hp_low: 300
hp_high: 3000
bandwidth: 3000
order: 6
